"""
Constantes da aplicação
"""

# Status de alunos
ALUNO_STATUS_ATIVO = 'ativo'
ALUNO_STATUS_TRANCADO = 'trancado'
ALUNO_STATUS_FORMADO = 'formado'
ALUNO_STATUS_CANCELADO = 'cancelado'

ALUNO_STATUSES = [
    ALUNO_STATUS_ATIVO,
    ALUNO_STATUS_TRANCADO,
    ALUNO_STATUS_FORMADO,
    ALUNO_STATUS_CANCELADO,
]

# Status de requerimentos
REQUERIMENTO_STATUS_PENDENTE = 'pendente'
REQUERIMENTO_STATUS_PROCESSANDO = 'processando'
REQUERIMENTO_STATUS_CONCLUIDO = 'concluido'
REQUERIMENTO_STATUS_REJEITADO = 'rejeitado'

REQUERIMENTO_STATUSES = [
    REQUERIMENTO_STATUS_PENDENTE,
    REQUERIMENTO_STATUS_PROCESSANDO,
    REQUERIMENTO_STATUS_CONCLUIDO,
    REQUERIMENTO_STATUS_REJEITADO,
]

# Tipos de requerimento
REQUERIMENTO_TIPO_ADICAO_MATERIA = 'adicao_materia'
REQUERIMENTO_TIPO_REMOCAO_MATERIA = 'remocao_materia'
REQUERIMENTO_TIPO_DECLARACAO = 'declaracao'
REQUERIMENTO_TIPO_BOLETO = 'boleto'

REQUERIMENTO_TIPOS = [
    REQUERIMENTO_TIPO_ADICAO_MATERIA,
    REQUERIMENTO_TIPO_REMOCAO_MATERIA,
    REQUERIMENTO_TIPO_DECLARACAO,
    REQUERIMENTO_TIPO_BOLETO,
]

# Tipos de declaração
DECLARACAO_TIPO_MATRICULA = 'matricula'
DECLARACAO_TIPO_FREQUENCIA = 'frequencia'
DECLARACAO_TIPO_CONCLUSAO = 'conclusao'

DECLARACAO_TIPOS = [
    DECLARACAO_TIPO_MATRICULA,
    DECLARACAO_TIPO_FREQUENCIA,
    DECLARACAO_TIPO_CONCLUSAO,
]

# Status de pagamento
PAGAMENTO_STATUS_PENDENTE = 'pendente'
PAGAMENTO_STATUS_PAGO = 'pago'
PAGAMENTO_STATUS_ATRASADO = 'atrasado'
PAGAMENTO_STATUS_CANCELADO = 'cancelado'

PAGAMENTO_STATUSES = [
    PAGAMENTO_STATUS_PENDENTE,
    PAGAMENTO_STATUS_PAGO,
    PAGAMENTO_STATUS_ATRASADO,
    PAGAMENTO_STATUS_CANCELADO,
]

# Tipos de pagamento
PAGAMENTO_TIPO_MENSALIDADE = 'mensalidade'
PAGAMENTO_TIPO_BOLETO_AVULSO = 'boleto_avulso'
PAGAMENTO_TIPO_TAXA = 'taxa'

PAGAMENTO_TIPOS = [
    PAGAMENTO_TIPO_MENSALIDADE,
    PAGAMENTO_TIPO_BOLETO_AVULSO,
    PAGAMENTO_TIPO_TAXA,
]

# Tipos de usuário
USUARIO_TIPO_ADMIN = 'admin'
USUARIO_TIPO_FUNCIONARIO = 'funcionario'
USUARIO_TIPO_PROFESSOR = 'professor'

USUARIO_TIPOS = [
    USUARIO_TIPO_ADMIN,
    USUARIO_TIPO_FUNCIONARIO,
    USUARIO_TIPO_PROFESSOR,
]

# Validações
MIN_SENHA_LENGTH = 4
MAX_SENHA_LENGTH = 128
MIN_CPF_LENGTH = 11
MAX_EMAIL_LENGTH = 100

# Database
ITEMS_PER_PAGE = 20
